mappings:
- stationId: 1
  templateId: legacy-ni-default
  version: 1
  bindings:
    V1:
      device: Dev1
      moduleType: DO
      channel: 0
      direction: OUT
      invert: false
    V2:
      device: Dev1
      moduleType: DO
      channel: 1
      direction: OUT
      invert: false
    V3:
      device: Dev1
      moduleType: DO
      channel: 2
      direction: OUT
      invert: false
    COMPRESSOR:
      device: Dev1
      moduleType: DO
      channel: 3
      direction: OUT
      invert: false
    P_SENSOR:
      device: Dev1
      moduleType: AI
      channel: 0
      direction: IN
      invert: false
    COUNTER_PWR:
      device: Dev1
      moduleType: DO
      channel: 5
      direction: OUT
      invert: false
    COUNTER_SIG:
      device: Dev1
      moduleType: DO
      channel: 6
      direction: OUT
      invert: false
    BUZZER:
      device: Dev1
      moduleType: DO
      channel: 7
      direction: OUT
      invert: false
- stationId: 2
  templateId: legacy-ni-default
  version: 1
  bindings:
    V1:
      device: Dev1
      moduleType: DO
      channel: 0
      direction: OUT
      invert: false
    V2:
      device: Dev1
      moduleType: DO
      channel: 1
      direction: OUT
      invert: false
    V3:
      device: Dev1
      moduleType: DO
      channel: 2
      direction: OUT
      invert: false
    COMPRESSOR:
      device: Dev1
      moduleType: DO
      channel: 3
      direction: OUT
      invert: false
    P_SENSOR:
      device: Dev1
      moduleType: AI
      channel: 0
      direction: IN
      invert: false
    COUNTER_PWR:
      device: Dev1
      moduleType: DO
      channel: 5
      direction: OUT
      invert: false
    COUNTER_SIG:
      device: Dev1
      moduleType: DO
      channel: 6
      direction: OUT
      invert: false
    BUZZER:
      device: Dev1
      moduleType: DO
      channel: 7
      direction: OUT
      invert: false
- stationId: 3
  templateId: legacy-ni-default
  version: 1
  bindings:
    V1:
      device: Dev1
      moduleType: DO
      channel: 0
      direction: OUT
      invert: false
    V2:
      device: Dev1
      moduleType: DO
      channel: 1
      direction: OUT
      invert: false
    V3:
      device: Dev1
      moduleType: DO
      channel: 2
      direction: OUT
      invert: false
    COMPRESSOR:
      device: Dev1
      moduleType: DO
      channel: 3
      direction: OUT
      invert: false
    P_SENSOR:
      device: Dev1
      moduleType: AI
      channel: 0
      direction: IN
      invert: false
    COUNTER_PWR:
      device: Dev1
      moduleType: DO
      channel: 5
      direction: OUT
      invert: false
    COUNTER_SIG:
      device: Dev1
      moduleType: DO
      channel: 6
      direction: OUT
      invert: false
    BUZZER:
      device: Dev1
      moduleType: DO
      channel: 7
      direction: OUT
      invert: false
- stationId: 4
  templateId: legacy-ni-default
  version: 1
  bindings:
    V1:
      device: Dev1
      moduleType: DO
      channel: 0
      direction: OUT
      invert: false
    V2:
      device: Dev1
      moduleType: DO
      channel: 1
      direction: OUT
      invert: false
    V3:
      device: Dev1
      moduleType: DO
      channel: 2
      direction: OUT
      invert: false
    COMPRESSOR:
      device: Dev1
      moduleType: DO
      channel: 3
      direction: OUT
      invert: false
    P_SENSOR:
      device: Dev1
      moduleType: AI
      channel: 0
      direction: IN
      invert: false
    COUNTER_PWR:
      device: Dev1
      moduleType: DO
      channel: 5
      direction: OUT
      invert: false
    COUNTER_SIG:
      device: Dev1
      moduleType: DO
      channel: 6
      direction: OUT
      invert: false
    BUZZER:
      device: Dev1
      moduleType: DO
      channel: 7
      direction: OUT
      invert: false
- stationId: 5
  templateId: legacy-ni-default
  version: 1
  bindings:
    V1:
      device: Dev1
      moduleType: DO
      channel: 0
      direction: OUT
      invert: false
    V2:
      device: Dev1
      moduleType: DO
      channel: 1
      direction: OUT
      invert: false
    V3:
      device: Dev1
      moduleType: DO
      channel: 2
      direction: OUT
      invert: false
    COMPRESSOR:
      device: Dev1
      moduleType: DO
      channel: 3
      direction: OUT
      invert: false
    P_SENSOR:
      device: Dev1
      moduleType: AI
      channel: 0
      direction: IN
      invert: false
    COUNTER_PWR:
      device: Dev1
      moduleType: DO
      channel: 5
      direction: OUT
      invert: false
    COUNTER_SIG:
      device: Dev1
      moduleType: DO
      channel: 6
      direction: OUT
      invert: false
    BUZZER:
      device: Dev1
      moduleType: DO
      channel: 7
      direction: OUT
      invert: false
- stationId: 6
  templateId: legacy-ni-default
  version: 1
  bindings:
    V1:
      device: Dev1
      moduleType: DO
      channel: 0
      direction: OUT
      invert: false
    V2:
      device: Dev1
      moduleType: DO
      channel: 1
      direction: OUT
      invert: false
    V3:
      device: Dev1
      moduleType: DO
      channel: 2
      direction: OUT
      invert: false
    COMPRESSOR:
      device: Dev1
      moduleType: DO
      channel: 3
      direction: OUT
      invert: false
    P_SENSOR:
      device: Dev1
      moduleType: AI
      channel: 0
      direction: IN
      invert: false
    COUNTER_PWR:
      device: Dev1
      moduleType: DO
      channel: 5
      direction: OUT
      invert: false
    COUNTER_SIG:
      device: Dev1
      moduleType: DO
      channel: 6
      direction: OUT
      invert: false
    BUZZER:
      device: Dev1
      moduleType: DO
      channel: 7
      direction: OUT
      invert: false
- stationId: 7
  templateId: legacy-ni-default
  version: 1
  bindings:
    V1:
      device: Dev1
      moduleType: DO
      channel: 0
      direction: OUT
      invert: false
    V2:
      device: Dev1
      moduleType: DO
      channel: 1
      direction: OUT
      invert: false
    V3:
      device: Dev1
      moduleType: DO
      channel: 2
      direction: OUT
      invert: false
    COMPRESSOR:
      device: Dev1
      moduleType: DO
      channel: 3
      direction: OUT
      invert: false
    P_SENSOR:
      device: Dev1
      moduleType: AI
      channel: 0
      direction: IN
      invert: false
    COUNTER_PWR:
      device: Dev1
      moduleType: DO
      channel: 5
      direction: OUT
      invert: false
    COUNTER_SIG:
      device: Dev1
      moduleType: DO
      channel: 6
      direction: OUT
      invert: false
    BUZZER:
      device: Dev1
      moduleType: DO
      channel: 7
      direction: OUT
      invert: false
- stationId: 8
  templateId: legacy-ni-default
  version: 1
  bindings:
    V1:
      device: Dev1
      moduleType: DO
      channel: 0
      direction: OUT
      invert: false
    V2:
      device: Dev1
      moduleType: DO
      channel: 1
      direction: OUT
      invert: false
    V3:
      device: Dev1
      moduleType: DO
      channel: 2
      direction: OUT
      invert: false
    COMPRESSOR:
      device: Dev1
      moduleType: DO
      channel: 3
      direction: OUT
      invert: false
    P_SENSOR:
      device: Dev1
      moduleType: AI
      channel: 0
      direction: IN
      invert: false
    COUNTER_PWR:
      device: Dev1
      moduleType: DO
      channel: 5
      direction: OUT
      invert: false
    COUNTER_SIG:
      device: Dev1
      moduleType: DO
      channel: 6
      direction: OUT
      invert: false
    BUZZER:
      device: Dev1
      moduleType: DO
      channel: 7
      direction: OUT
      invert: false
